global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'gameservice'
    static_configs:
      - targets: ['gameservice:80']
    metrics_path: '/metrics'
    scrape_interval: 15s

  - job_name: 'recyclerservice'
    static_configs:
      - targets: ['recyclerservice:80']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'truckservice'
    static_configs:
      - targets: ['truckservice:80']
    metrics_path: '/metrics'
    scrape_interval: 15s

  - job_name: 'headquartersservice'
    static_configs:
      - targets: ['headquartersservice:80']
    metrics_path: '/metrics'
    scrape_interval: 15s

  - job_name: 'recyclingplantservice'
    static_configs:
      - targets: ['recyclingplantservice:80']
    metrics_path: '/metrics'
    scrape_interval: 15s

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']

  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']

  - job_name: 'frontend'
    static_configs:
      - targets: ['frontend:3000']
    metrics_path: '/metrics'
    scrape_interval: 15s

  - job_name: 'bottle-tycoon-gameservice-postgres'
    static_configs:
      - targets: ['gameservice-postgres-exporter:9187']
    scrape_interval: 15s

  - job_name: 'bottle-tycoon-truck-postgres'
    static_configs:
      - targets: ['truck-postgres-exporter:9187']
    scrape_interval: 15s

  - job_name: 'bottle-tycoon-recycler-postgres'
    static_configs:
      - targets: ['recycler-postgres-exporter:9187']
    scrape_interval: 15s

  - job_name: 'bottle-tycoon-recyclingplant-postgres'
    static_configs:
      - targets: ['recyclingplant-postgres-exporter:9187']
    scrape_interval: 15s